version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.0.0
jobs:
  build:
    docker:
      - image: amazonlinux
    working_directory: ~/repo
    aws-cli-cred-setup:
      executor: aws-cli/default
      steps: 
        - aws-cli/setup:
            aws-access-key-id: AWS_ACCESS_KEY
            aws-secret-access-key: AWS_ACCESS_SECRET
            aws-region: AWS_REGION_NAME
    steps:
      - checkout
      - run:
          name: Install Python 3.8
          command: |
            dnf install sudo -y
            sudo dnf groupinstall "Development Tools" -y
            sudo dnf install -y openssl-devel bzip2-devel libffi-devel zlib-devel
            cd /opt
            sudo dnf install wget -y
            sudo dnf install tar -y
            sudo wget https://www.python.org/ftp/python/3.8.12/Python-3.8.12.tgz
            sudo tar xzf Python-3.8.12.tgz
            cd Python-3.8.12
            sudo ./configure --enable-optimizations
            sudo make altinstall
            sudo rm -rf /opt/Python-3.8.12
            python3 --version
      # - run:
      #     name: Install AWS CLI
      #     command: |
      #       sudo dnf install python3-pip -y
      #       pip install awscli
      - run:
          name: Install Hugo
          command: |
            cp hugo_installation_config.txt /etc/yum.repos.d/CentOS-hugo.repo
            yum install -y hugo
            hugo version
      - run:
          name: Build Website
          command: |
            cd voiceTestWebSite
            hugo
      - deploy:
          command:
            aws s3 sync --delete --acl "public-read" --sse "AES256" voiceTestWebSite/public/ s3://polly-test-0810
workflows:
  aws-cli-hugo:
    jobs:
      - build:
          context: aws
