version: 2
jobs:
  build:
    docker:
      - image: amazonlinux

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install Python 3.8
          command: |
            dnf install sudo
            cd /opt
            sudo wget https://www.python.org/ftp/python/3.8.12/Python-3.8.12.tgz
            sudo tar xzf Python-3.8.12.tgz
            cd Python-3.8.12
            sudo ./configure --enable-optimizations
            sudo make altinstall
            sudo rm -rf /opt/Python-3.8.12
            python3 --version

      - run:
          name: Install AWS CLI
          command:
            pip install awscli

      - run:
          name: Install Hugo
          command: |
            cp hugo_installation_config.txt /etc/yum.repos.d/CentOS-hugo.repo
            yum install -y hugo
            hugo version