version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.0.0
jobs:
  build:
    docker:
      - image: amazonlinux
    working_directory: ~/repo

    steps:
      - checkout
      
      - run:
          name: Install Python 3.8
          command: |
            dnf install sudo -y
            sudo dnf groupinstall "Development Tools" -y
            sudo dnf install -y openssl-devel bzip2-devel libffi-devel zlib-devel
            cd /opt
            sudo dnf install wget -y
            sudo dnf install tar -y
            sudo dnf install unzip -y
            sudo wget https://www.python.org/ftp/python/3.8.12/Python-3.8.12.tgz
            sudo tar xzf Python-3.8.12.tgz
            cd Python-3.8.12
            sudo ./configure --enable-optimizations
            sudo make altinstall
            sudo rm -rf /opt/Python-3.8.12
            python3 --version
      - aws-cli/setup
      - run:
          name: Install Hugo
          command: |
            cp hugo_installation_config.txt /etc/yum.repos.d/CentOS-hugo.repo
            yum install -y hugo
            hugo version
      - run:
          name: Add articles to be converted to audio by Polly
          command: |
            aws s3 sync voiceTestWebSite/articles/ s3://polly-article-test-0810/articles/
      - run:
          name: Build Website
          command: |
            cd voiceTestWebSite
            hugo
      - deploy:
          command: |
            aws configure list
            aws s3 sync --delete --acl "public-read" --sse "AES256" voiceTestWebSite/public/ s3://polly-test-0810

  lambda_build:
    docker:
      - image: amazonlinux
    working_directory: ~/repo

    steps:
      - checkout  
      - run:
          name: Install Python 3.8
          command: |
            dnf install sudo -y
            sudo dnf groupinstall "Development Tools" -y
            sudo dnf install -y openssl-devel bzip2-devel libffi-devel zlib-devel
            cd /opt
            sudo dnf install wget -y
            sudo dnf install tar -y
            sudo dnf install unzip -y
            sudo wget https://www.python.org/ftp/python/3.8.12/Python-3.8.12.tgz
            sudo tar xzf Python-3.8.12.tgz
            cd Python-3.8.12
            sudo ./configure --enable-optimizations
            sudo make altinstall
            sudo rm -rf /opt/Python-3.8.12
            python3 --version
      - aws-cli/setup
      - run:
          name: Create Lamda Package
          command: |
            yum install -y zip
            cd polly_lambda && zip -r ../sam-config/lambda.zip ./*
            cd ..
            bash -x lambda_libraries.sh
      - run:
          name: Upload Lambda Code to S3
          command: |
            aws cloudformation package \
            --template-file sam-config/template.yaml \
            --s3-bucket route-to-excellence-code-bucket \
            --output-template-file sam-config/packaged-template.yaml
      - run:
          name: Deploy Lambda Changes
          command: |
            aws cloudformation deploy \
            --template-file sam-config/packaged-template.yaml \
            --stack-name polly-lambda-stack \
            --capabilities CAPABILITY_IAM \
            --region ap-northeast-1
workflows:
  version: 2
  build-lambda-and-website:
    jobs:
      - lambda_build
      - build:
          requires:
            - lambda_build
